services:
  # MySQL コンテナ
  db:
    image: mysql:8.0
    container_name: week-kakeibo-db
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: budget_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # PHPMyAdmin コンテナ
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: week-kakeibo-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: mysecretpassword
    depends_on:
      - db
volumes:
  db_data: